spring:
  datasource:
    url: jdbc:mysql://localhost:3306/checkoutcheckout?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    com.toy.checkoutcheckout: DEBUG

jwt:
  secret: checkoutcheckoutSecretKey1234567890abcdefghijklmnopqrstuvwxyz
  token-validity-in-seconds: 86400 # 1일

server:
  port: 8080
  servlet:
    context-path: /

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  prometheus:
    metrics:
      export:
        enabled: true
