spring:
  datasource:
    url: jdbc:mysql://localhost:3306/checkoutcheckout?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    
  redis:
    host: localhost
    port: 6379

jwt:
  secret: checkoutcheckoutSecretKey1234567890abcdefghijklmnopqrstuvwxyz
  token-validity-in-seconds: 86400 # 1일

server:
  port: 8080
  servlet:
    context-path: /
