apiVersion: v1
kind: Service
metadata:
  name: springboot-app
  labels:
    app: springboot-app
spec:
  selector:
    app: springboot-app
  ports:
    - port: 8080
      targetPort: 8080
      name: web
  type: ClusterIP